trigger:
- main
pool:
  vmImage: ubuntu-latest
stages:
- stage: build
  variables:
    environment: build
  jobs: 
  - job: firstjob
    steps:
      - bash: echo first build job
      - bash: echo $(environment) running
  - job: secondjob
    steps:
      - bash: echo second  build job
      - bash: echo second build job fully completed

- stage: dev
  jobs: 
  - job: devjobs
    steps:
      - bash: echo "Start devDeploy job"
  - deployment: devDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to dev

- stage: test
  jobs: 
  - job: testjobs
    steps:
      - bash: echo "Start devDeploy job"
  - deployment: devDeployJob
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to dev
  dependsOn: dev

- stage: pprd
  jobs: 
  - job: devjobs
    steps:
      - bash: echo "Start devDeploy job"
  - deployment: preprdDeployJob
    environment: preprd
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to dev
  dependsOn: dev

- stage: prd
  jobs: 
  - job: devjobs
    steps:
      - bash: echo "Start prdDeploy job"
  - deployment: devDeployJob
    environment: prd
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to dev
  dependsOn: pprd





  


  
