trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs: 
  - job: firstjob
    steps:
      - bash: first build job
  - job: secondjob
    steps:
      - bash: second  build job
      - bash : second build job fully completed




  


  
