trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs: 
  - job: firstjob
    steps:
      - bash: first build job
  - job: secondjob
    steps:
      - bash: second  build job

- stage: dev
  jobs: 
  - job: devjobs
    steps:
      - bash: dev job running 

- stage: test
  jobs: 
  - job: testjobs
    steps:
      - bash: test job running 
- stage: preprd
  jobs: 
  - job: preprdjobs
    steps:
      - bash: tpreprd job running 
- stage: prd
  jobs: 
  - job: prdjob
    steps:
      - bash: prd job running 




  


  
