trigger:
- main
pool:
  vmImage: ubuntu-latest
stages:
- stage: build
  variables:
    environment: build
  jobs: 
  - job: firstjob
    steps:
      - bash: echo first build job
      - bash: echo $(environment) running
  - job: secondjob
    steps:
      - bash: echo second  build job
      - bash: echo second build job fully completed

- stage: devDeploy
  jobs: 
  - job: devjobs
    steps:
      - bash: echo "Start devDeploy job"
  - deployment: devDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to dev

- stage: test
  jobs: 
  - job: testjobs
    steps:
      - bash: echo "Start devDeploy job"
  - deployment: devDeployJob
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to dev
  dependsOn: dev

- stage: preprd
    jobs: 
  - job: devjobs
    steps:
      - bash: echo "Start devDeploy job"
  - deployment: devDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to dev
 dependsOn: test

- stage: prd
  variables: 
   environment: preprd
  jobs: 
  - job: prdjob
    steps:
      - bash: echo $(environment) job running 





  


  
