trigger:
- main
pool:
  vmImage: ubuntu-latest
stages:
- stage: build
  variables:
    environment: build
  jobs: 
  - job: firstjob
    steps:
      - bash: echo first build job
      - bash: echo $(environment) running
  - job: secondjob
    steps:
      - bash: echo second  build job
      - bash: echo second build job fully completed
- stage: devDeploy
  jobs: 
  - job: devjobs
    steps:
      - bash: echo "Start devDeploy job"
  - deployment: devDeployJob
    envionment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          -script: echo deploy to dev
- stage: test
  variables: 
    environment: test
  dependsOn: build
  jobs: 
  - job: testjobs
    steps:
      - bash: echo $(environment) job running 

- stage: preprd
  variables: 
   environment: preprd
  dependsOn: test
  jobs: 
  - job: preprdjobs
    steps:
     - bash: echo $(environment) job running 
- stage: prd
  variables: 
   environment: preprd
  jobs: 
  - job: prdjob
    steps:
      - bash: echo $(environment) job running 





  


  
