trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs: 
  - job: firstjob
    steps:
      - bash: echo first build job
      - bash: $(PipelineLevelVariable)
  - job: secondjob
    steps:
      - bash: echo second  build job
      - bash: echo second build job fully completed


- stage: dev
  variables: 
    environment: dev
  dependsOn: build
  jobs: 
  - job: devjobs
    steps:
      - bash: echo $(environmet) job running 

- stage: test
  variables: 
    environment: test
  dependsOn: build
  jobs: 
  - job: testjobs
    steps:
      - bash: echo $(environment) job running 

- stage: preprd
  variables: 
   environment: preprd
  dependsOn: test
  jobs: 
  - job: preprdjobs
    steps:
     - bash: echo $(environment) job running 
- stage: prd
  variables: 
   environment: preprd
  jobs: 
  - job: prdjob
    steps:
      - bash: echo $(environment) job running 





  


  
