trigger:
- main
pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'kundan-connection'
    backendAzureRmResourceGroupName: 'Kundan-rc-grp'
    backendAzureRmStorageAccountName: 'kundatflogs'
    backendAzureRmContainerName: 'kundancontainer'
    backendAzureRmKey: 'QGSUoxpsOgNZQ740u6fR1sCmtJAuj6xtg8s3bwEMcgzZtRa9hRb/t4kHGAS9XlGc/JMDJXRhcYKE+AStwqJgXg=='
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'kundan-connection'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'

