trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'kundan-connection'
    backendAzureRmResourceGroupName: 'Kundan-rc-grp'
    backendAzureRmStorageAccountName: 'kundatflogs'
    backendAzureRmContainerName: 'kundancontainer'
    backendAzureRmKey: '/nZ/JeKablKJyj0y2SEKQWenHhZwVnghvPfRsK/vBhbf10NghUE3GX8JoxEyG1dNCFSOzWCi1mJR+AStJ8kzxA=='

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'validate'