trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs: 
  - job: firstjob
    steps:
      - bash: first build job
  - job: firstjob
    steps:
      - bash: second  build job

- stage: dev
jobs: 
  - job: dev jobs
    steps:
      - bash: dev job running 

- stage: test
- stage: preprod
- stage: prd



  


  
