trigger:
- main

pool:
  vmImage: ubuntu-latest

  #pipelines > stages > jobs > task(Steps)
jobs:
- job: job1
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

- job: job2
  steps:
  - script: echo job2!
  


  
