trigger:
- main
pool:
  vmImage: ubuntu-latest

stages:
- stage: default
  jobs:
  - job: defaultJob
steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'kundan-connection'
    backendAzureRmResourceGroupName: 'Kundan-rc-grp'
    backendAzureRmStorageAccountName: 'kundatflogs'
    backendAzureRmContainerName: 'kundancontainer'
    backendAzureRmKey: '/nZ/JeKablKJyj0y2SEKQWenHhZwVnghvPfRsK/vBhbf10NghUE3GX8JoxEyG1dNCFSOzWCi1mJR+AStJ8kzxA=='

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'kundan-connection'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'kundan-connection'

- stage: Test
  jobs:
  - job: TestJob
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'kundan-connection'
    backendAzureRmResourceGroupName: 'Kundan-rc-grp'
    backendAzureRmStorageAccountName: 'kundatflogs'
    backendAzureRmContainerName: 'kundancontainer'
    backendAzureRmKey: '/nZ/JeKablKJyj0y2SEKQWenHhZwVnghvPfRsK/vBhbf10NghUE3GX8JoxEyG1dNCFSOzWCi1mJR+AStJ8kzxA=='

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-out test.tfplan'
    environmentServiceNameAzureRM: 'kundan-connection'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: 'test.tfplan'
    environmentServiceNameAzureRM: 'kundan-connection'